[Proposal] Exception handling and library structure
Add some new types, a small layer on top of Result, and an example of how to structure a library.

# Main ideas

1.
UserError vs. InternalError

2.
API (thin conversion layer) vs. implementation (bulk of our code)


2. Convenient Result type for internal exceptions
`EResult = Result[..., Exception]`


Do this as low as possible
```
@resultify_exceptions
def ...
```


Can use this instead of just `Err()` for better stack traces

`make_err(my_exception)`


3. Convert back to Exception for APIs

```
@careful_do_you_really_want_to_call_me_return_or_raise
def ...
```


## Example Structure

User code
-> LM API (return normal value or raise)
-> LM impl (use Result internally)
-> Wrap any 3rd party calls in a Result


The example has:
- api.py, an example LM API (in the spirit of a header file)
  - This uses the Result layer to unwrap back into nice exceptions
- lib.py, the implementation file, uses Result operations internally


## Distinguish between UserError and InternalError

Full stack traces for InternalError for bug reports, else just the part relevant to caller.

By definition, InternalError is always a bug - it's always unexpected.
If an exception is not a user error, we should either turn it into one or recover somehow.


# Try running the example user app

- Many potential bugs involving unhandled exceptional cases are caught by pyright.
- UserErrors are shown as such.
- One class of bugs (raised exception) is impossible to detect statically,
but full stack trace is shown



```
python python/examples/library_structure/user_app.py --key=good

Running example with key: good
Value: 2

```

```
# Intentional bug example
python/examples/library_structure/user_app.py --key=bug

lastmile_utils.lib.core.utils.InternalError:
            Unexpected error!
            An Exception was caught inside
            careful_do_you_really_want_to_call_me_return_or_raise().

            This means there is probably a missing application of the
            resultify_exceptions() decorator. Please see the stack trace.

            Please file a bug report...

```

```
# User error

python python/examples/library_structure/user_app.py --key=bad-key


lastmile_utils.lib.core.utils.UserError: Can't preprocess key bad-key
```


```
# Recoverable internal exception

python python/examples/library_structure/user_app.py --key=bad-value --default-int=5
Running example with key: bad-value
Value: 5


```